// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poprawa.Data;

#nullable disable

namespace Poprawa.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250616113557_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Poprawa.Models.Backpack", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Backpack");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CharacterId = 1,
                            Amount = 1
                        },
                        new
                        {
                            ItemId = 4,
                            CharacterId = 2,
                            Amount = 1
                        },
                        new
                        {
                            ItemId = 3,
                            CharacterId = 3,
                            Amount = 1
                        },
                        new
                        {
                            ItemId = 2,
                            CharacterId = 3,
                            Amount = 1
                        });
                });

            modelBuilder.Entity("Poprawa.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            CurrentWeight = 12,
                            FirstName = "Aragorn",
                            LastName = "Son of Arathorn",
                            MaxWeight = 50
                        },
                        new
                        {
                            CharacterId = 2,
                            CurrentWeight = 5,
                            FirstName = "Legolas",
                            LastName = "Greenleaf",
                            MaxWeight = 40
                        },
                        new
                        {
                            CharacterId = 3,
                            CurrentWeight = 25,
                            FirstName = "Gimli",
                            LastName = "Son of Gloin",
                            MaxWeight = 60
                        });
                });

            modelBuilder.Entity("Poprawa.Models.Character_Title", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CharacterId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("Character_Title");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            TitleId = 1,
                            AcquiredAt = new DateTime(2020, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitleId = 2,
                            AcquiredAt = new DateTime(2021, 1, 15, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 3,
                            TitleId = 3,
                            AcquiredAt = new DateTime(2019, 9, 20, 8, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Poprawa.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Name = "Sword",
                            Weight = 12
                        },
                        new
                        {
                            ItemId = 2,
                            Name = "Shield",
                            Weight = 20
                        },
                        new
                        {
                            ItemId = 3,
                            Name = "Axe",
                            Weight = 15
                        },
                        new
                        {
                            ItemId = 4,
                            Name = "Bow",
                            Weight = 8
                        });
                });

            modelBuilder.Entity("Poprawa.Models.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TitleId");

                    b.ToTable("Title");

                    b.HasData(
                        new
                        {
                            TitleId = 1,
                            Name = "Ranger"
                        },
                        new
                        {
                            TitleId = 2,
                            Name = "Elven Prince"
                        },
                        new
                        {
                            TitleId = 3,
                            Name = "Dwarf Warrior"
                        });
                });

            modelBuilder.Entity("Poprawa.Models.Backpack", b =>
                {
                    b.HasOne("Poprawa.Models.Character", "Character")
                        .WithMany("Backpacks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poprawa.Models.Item", "Item")
                        .WithMany("Backpacks")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Poprawa.Models.Character_Title", b =>
                {
                    b.HasOne("Poprawa.Models.Character", "Character")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poprawa.Models.Title", "Title")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Poprawa.Models.Character", b =>
                {
                    b.Navigation("Backpacks");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("Poprawa.Models.Item", b =>
                {
                    b.Navigation("Backpacks");
                });

            modelBuilder.Entity("Poprawa.Models.Title", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
